### ISSUE TITLE
Publish on pypi.org

### ISSUE THREAD

**Issue by N0K0** [CheckPointSW/cp_mgmt_api_python_sdk#18]
Hi,
I can't seem to find this package on Pypi.
Is published at all?

**Comment by chkp-amiads** [comment]
No. Due to organization policy we decided it will be published at our github account only.
See our README to learn how to install our SDK.

You can use: _pip install git+https://github.com/CheckPointSW/cp_mgmt_api_python_sdk_ 

If you don't have git, you can:
- Download the SDK by using the ‘_Download ZIP_’ button 
- unzip it. 
- Navigate to .../cp_mgmt_api_python_sdk/ directory and run: _pip install ._

**Comment by N0K0** [comment]
Thanks for the quick response!

Checkpoint should consider hosting its own simple repository so that repository management tools like Artifactory may manage the package in a local cache. This would also make sure that the latest up to date version of the package is used.
