### ISSUE TITLE
why we don't upload this to pypi

### ISSUE THREAD

**Issue by xiaopeng163** [CheckPointSW/cp_mgmt_api_python_sdk#20]
we can upload this to pypi and it will be easier to download and install through pip install

**Comment by chkp-yaelg** [comment]
Hi @xiaopeng163 ,
Due to organization policy we decided it will be published at our github account only.
See our README to learn how to install our SDK.

You can use: pip install git+https://github.com/CheckPointSW/cp_mgmt_api_python_sdk

If you don't have git, you can:
- Download the SDK by using the ‘Download ZIP’ button
- unzip it.
- Navigate to .../cp_mgmt_api_python_sdk/ directory and run: pip install .

**Comment by xiaopeng163** [comment]
thanks. if so, could we add version to the repo, we don't want to install master branch code each time

but tag it 

with git
```
$ pip install git+https://github.com/CheckPointSW/cp_mgmt_api_python_sdk@v2.1.0
````
or from source bundle
```
$ pip install https://github.com/CheckPointSW/cp_mgmt_api_python_sdk/archive/v2.1.0.tar.gz
```

**Comment by chkp-yaelg** [comment]
Thank you for your suggestion!

You can try it with version v1.1
We will update the releases with new fixes and new features.

Regards,
Yael

**Comment by vbrozik** [comment]
@chkp-yaelg I am not able to figure out what could be the reasons for not publishing the library in the standard Python repository PyPI. Could you please explain them?

Using PyPI allows the software to work even if GitHub decides to change something of if you decide to move to a different source code repository. PyPI allows much more flexibility operating with software versions in the dependencies.
