### ISSUE TITLE
package name collision with cpapi / OpenMaya 

### ISSUE THREAD

**Issue by amoruck** [CheckPointSW/cp_mgmt_api_python_sdk#42]
Hello, 
There is another package with the same name already published to pypi (https://pypi.org/project/cpapi/), so if someone accidentally type "pip install cpapi" after seeing a message "No module named 'cpapi'" he gets this OpenMaya package (why is it called cpapi - I don't know, I hope it's not malicious but it would be possible to use it as such). 
It is kind of annoying that your package is not available via pypi, as it is hard to use it in another packages as dependency, also installing from git is not always an option; would it be possible to give the package unique name and publish it to pypi ?

**Comment by chkp-edenbr** [comment]
Hi,

A while back we couldn't publish it due to organization policy. I'll check again and update you if things have changed.

In the meantime, you can use: pip install git+https://github.com/CheckPointSW/cp_mgmt_api_python_sdk

If you don't have git, you can:

Download the SDK by using the ‘Download ZIP’ button
unzip it.
Navigate to .../cp_mgmt_api_python_sdk/ directory and run: pip install .

**Comment by chkp-edenbr** [comment]
Hi,

The package is now available in PyPI as cp-mgmt-api-sdk:
https://pypi.org/project/cp-mgmt-api-sdk/

Regards,
Eden

**Comment by amoruck** [comment]
Wow, great!!! thank you very much!
